### ISSUE TITLE
Nested model validations

### ISSUE THREAD

**Issue by alliedarmour** [jrochkind/attr_json#111]
Hey again, sorry for bothering you one last time

I read the docs about validations and got one last question.
The validation is working, but I also want to show the validation messages translated by I18n. 

Now, if I validate my "associated" address model like this:

```
class Address
    include AttrJson::Model

    attr_json :id, :integer 

    attr_json :use, :string
    attr_json :type, :string
    attr_json :text, :string
    attr_json :line, :string, array: true
    attr_json :city, :string
    attr_json :district, :string
    attr_json :state, :string
    attr_json :postalCode, :string
    attr_json :country, :string

    validates :postalCode, numericality: true
end
```

And then getting the errors the regular Rails way like tha (object is the form object here, `patient` in this case)t:

```
<% object.errors.full_messages.each do |msg| %
    <li class="white-text"><strong><%= msg %></strong></li>
<% end %>
```

Then I get the message "Address is not valid", which is fine. The next message "is not a number" is nested deeper in the according array/hash structure and therefore not shown when I just use this method.

Is there any way I could grab these messages in the standard way aswell or do you think that won't work because of the missin g `has_one` or `has_many` dependency?

**Comment by jrochkind** [comment]
Sorry, I'm not really sure. How would you do this ordinarily in Rails? If how you would do it ordinarily in Rails isn't working here, and you can figure out a PR to make it work, I'm happy to review it! 

I tried to just do the ordinary rails thing here. I know Rails recently (6.1? 6.0? I forget) changed how validation worked to make it a bit more powerful. It's possible that new way isn't working here? Not sure. 

I haven't looked at this code in a bit and just don't know, sorry!

**Comment by jrochkind** [comment]
Closing for now, a couple years later, feel free to comment again if you have more info or ideas.
