### ISSUE TITLE
Get parent Model inside Attr_json nested model. 

### ISSUE THREAD

**Issue by guilhermegazzinelli** [jrochkind/attr_json#113]
I'm trying to implement an relation to parent model, like `belongs_to` behavior inside an 'AttrJson::Model', there's an "gem Way" to do that?

My current solution is to pass the parent model to the method I'm calling, but this leads to others questions and more complexity. Like: `AttrJsonModel.new().called_method(parent, *other_args)`

But it's in some way possible to do inside method:
```ruby
class Model
  include AttrJson::Model
  
  def called_method args
    ...  
    self.parent_model
    ...
  end
``` 
Could you share some thoughts about this need?

Thanks for all.

**Comment by jrochkind** [comment]
Thanks for trying out attr_json and asking a question! 

Ah, I see what you mean. The parent naturally has access to it's embedded children, but the children don't have access back up to the parent. 

There isn't any supported way to do that at present. I haven't been able to figure out a good way to implement it. So currently it's not supported.  I myself have not needed it. 

If you can figure out a simple and maintainable way to PR this to be built-in, I'd be willing to consider it -- but it might be tricky, not sure it's feasible. I am cautious of making this code any more complex or harder to maintain. The way we use the ActiveModel type serialization/deserialization system to implement... I'm not sure how feasible it is.

**Comment by guilhermegazzinelli** [comment]
Thanks for your reply @jrochkind !

I'll take a look at this feature and try to find a maintainable way.
