### ISSUE TITLE
How would you create a nested array attribute?

### ISSUE THREAD

**Issue by paulodeon** [jrochkind/attr_json#127]
In my case I need it to be an array of arrays of strings i.e. `[['asd', 'def'], ['qwe', 'ert']]`

**Comment by jrochkind** [comment]
There's no support for that specifically. 

You could maybe do 

   attr_json :something, ActiveModel::Type::Json.new

Which if it worked (that might not be exactly the right way to do it, but there should be some way) would let the value be *any* json-compatible value. It would not insist it was an array of array of strings, it would allow anything, but that should include the array of array of strings.

**Comment by paulodeon** [comment]
Thanks, that's what I ended up doing
