### ISSUE TITLE
Empty nested resource on edit form

### ISSUE THREAD

**Issue by tsipa88** [jrochkind/attr_json#129]
Hi and many thanks for your gem. 
It's really solved (almost) my problem. 
But for know i have a strange behavior (.
I've use your example, described here https://github.com/jrochkind/attr_json/tree/master/spec/internal.

What i get , - form rendered perfect,  all data passed to controller perfect, typing Document.last in console and see that all data looks perfect. But, when i try to render edit action - fields_for block is empty (like i'm creating new Document) and when i type Document.last.person_roles - it returns nil. If i use Document.last[:person_roles] - i can see perfect data...
What can be wrong? 

rails (5.2.5)
ruby 2.6.3
pg (0.21.0)
attr_json (1.3.0)
cocoon (1.2.15)

thanks.

**Comment by tsipa88** [comment]
Ok, i'm finally figured out what's the reason. 
I've used my own custom field in database instead of using `json_attributes` naming like in your example.
For now - everything works like a charm. 

Thanks again for perfect solution!

**Comment by jrochkind** [comment]
OK, I don't totally follow but glad you figured it out!
