### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by Bramjetten** [jrochkind/attr_json#134]
It looks like attr_json is working great on Rails 7, but the gemspec still requires activerecord < 7.0. Would it be possible to drop the upper limit entirely?

**Comment by jrochkind** [comment]
I don't like allowing unbounded upper, because can't predict the future,
and it's easy for that to mess up resolving in the future.  But yes it's
time for <8. I'm on vacation might take me a bit to get to it sorry!
