### ISSUE TITLE
AttrJson::Model object not storing

### ISSUE THREAD

**Issue by simmerz** [jrochkind/attr_json#146]
I have the following base model:

```ruby
class GlobalSetting < ApplicationRecord
  include AttrJson::Record
  include AttrJson::Record::QueryScopes

  attr_json :insurance, GlobalSettings::Insurance.to_type
end
```

with `GlobalSettings::Insurance` here:

```ruby
module GlobalSettings
  class Insurance
    include AttrJson::Model
    attr_json_config(bad_cast: :as_nil)

    attr_json :percentage, :integer
    attr_json :minimum, :integer
  end
end
```

When I attempt to create a new object and save it, it doesn't save the json data:

```
[1] pry(main)> gs = GlobalSetting.new insurance: GlobalSettings::Insurance.new(percentage: 15, minimum: 8)
=> #<GlobalSetting:0x00007fbb16766190
 id: nil,
 settings: nil,
 created_at: nil,
 updated_at: nil,
 json_attributes: {"insurance"=>#<GlobalSettings::Insurance:0x00007fbb169c8f78 @attributes={"percentage"=>15, "minimum"=>8}>}>
[2] pry(main)> gs.save
  TRANSACTION (0.2ms)  BEGIN
  GlobalSetting Create (1.0ms)  INSERT INTO "global_settings" ("settings", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["settings", nil], ["created_at", "2022-04-22 13:07:33.766521"], ["updated_at", "2022-04-22 13:07:33.766521"]]
  TRANSACTION (2.2ms)  COMMIT
=> true
[3] pry(main)> gs.insurance
=> #<GlobalSettings::Insurance:0x00007fbb16603fa0 @attributes={"percentage"=>15, "minimum"=>8}>
[4] pry(main)> gs.reload
  GlobalSetting Load (0.3ms)  SELECT "global_settings".* FROM "global_settings" WHERE "global_settings"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
=> #<GlobalSetting:0x00007fbb16766190
 id: 3,
 settings: nil,
 created_at: Fri, 22 Apr 2022 14:07:33.766521000 BST +01:00,
 updated_at: Fri, 22 Apr 2022 14:07:33.766521000 BST +01:00,
 json_attributes: {}>
[5] pry(main)> gs.insurance
=> nil
```

**Comment by jrochkind** [comment]
Thanks for the error report!  I'll try to find time to reproduce and debug. 

The only thing that looks at all unusual there to me is the `bad_cast: nil`, I wonder if it's a bug in that implementation.  Can you take take that out, and see if it it works without that, to give us more information about what's going on?

**Comment by simmerz** [comment]
No that doesn't appear to make any difference unfortunately.

**Comment by jrochkind** [comment]
OK thanks for checking!

Some time next week I will try to reproduce and debug. Since this _looks_ to me like a very ordinary example that I can't see any reason it wouldn't work... it's _possible_ I won't be able to reproduce because it may actually be related to something else going on in your app... If you wanted to try to make a stand-alone reproduction of the problem, that could save us all some time!  One way to do that would be to make a failing test case in the rspec of this project.

**Comment by simmerz** [comment]
I'll do that in a bit for sure. It did seem weird that seemingly basic behaviour didn't work.

**Comment by simmerz** [comment]
You know @jrochkind , sometimes I should get more sleep (or more ☕ ). It would help me somewhat if I named my column correctly...

But that does raise a possible issue - if there isn't a column named either `json_attributes` OR whatever the config defines it to be, then `AttrJson` doesn't barf at me to tell me.

Still, this one can be closed. Thank you so much for your time on it, despite it being completely unnecessary! 🙈

**Comment by jrochkind** [comment]
No problem, thank you!

I agree that I'd expect a raise with a missing/mis-named column, and it seems unfortunate there isn't one.   I'm surprised I haven't run into this before, how can I have never mis-named a column! 

I wonder what the built-in solutions like [serialize](https://api.rubyonrails.org/v7.0.0/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize) do in similar situation?
