### ISSUE TITLE
AttrJson::Record::Dirty: #will_save_change_to returns true when other attribute was changed

### ISSUE THREAD

**Issue by bemueller** [jrochkind/attr_json#148]
Hi,
I recently ran into an issue with AttrJson::Record::Dirty with an active record hook. The hook should extract and log changes of an attr_json field `mac` and was configured to be triggered only, if this field had changed (by using `#will_save_change_to_mac?` method). I wondered when some CI tests failed and found out, that this method returned `true` even when the record was saved and another attribute was modified afterwards.
Here's an example code to reproduce the issue:

```
class User < ApplicationRecord
  include AttrJson::Record
  include AttrJson::Record::Dirty

  attr_json :age, :integer
  attr_json :friends, :integer
end

2.7.3 :003 > user = User.create
2.7.3 :004 > user.attr_json_changes.will_save_change_to_age?
 => false
2.7.3 :005 > user.age = 18
 => 18
2.7.3 :006 > user.attr_json_changes.will_save_change_to_age?
 => true
2.7.3 :007 > user.save!
 => true
2.7.3 :008 > user.friends = 4
 => 4
2.7.3 :009 > user.attr_json_changes.will_save_change_to_age?
 => true
2.7.3 :010 > user.attr_json_changes.changes_to_save
 => {"friends"=>[nil, 4]}
```

I guess this is not the intended behavior, is it?

**Comment by simmerz** [comment]
This appears to be the case with `saved_change_to_attribute` too.

I have a model with:

```
attr_json :insurance, GlobalSettings::Insurance.to_type
attr_json :asset_protection, GlobalSettings::Insurance.to_type
```

When I change the `insurance` value, I get the following:

```
[7] pry(#<GlobalSetting>)> attr_json_changes.saved_changes
=> {"insurance"=>
  [#<GlobalSettings::Insurance:0x00007fd53e8f7468 @attributes={"percentage"=>15, "minimum"=>8}>,
   #<GlobalSettings::Insurance:0x00007fd54036c578
    @attributes={"percentage"=>30, "minimum"=>15},
    @errors=#<ActiveModel::Errors []>,
    @validation_context=nil>]}

[9] pry(#<GlobalSetting>)> attr_json_changes.saved_change_to_asset_protection
=> [#<GlobalSettings::Insurance:0x00007fd53e860928 @attributes={"percentage"=>15, "minimum"=>8}>,
 #<GlobalSettings::Insurance:0x00007fd54036c898
  @attributes={"percentage"=>15, "minimum"=>8},
  @errors=#<ActiveModel::Errors []>,
  @validation_context=nil>]

[10] pry(#<GlobalSetting>)> attr_json_changes.saved_change_to_asset_protection?
=> true
```

**Comment by jrochkind** [comment]
Hey, thanks for the error report. 

This does appear to be undesirable unplanned behavior. :( 

My overall plan for this features is to lean more heavily on Rails built-in attributes, so you can use ordinary Rails dirty-tracking with attr_json. I have done some work in that direction, and it looks prommissing. Attr_json was originally written for Rails 4.2 (!), and more things are possible now. Additionally, the `jsonb_acessor` gem models some things to imitate there. 

That would completely replace the existing `attr_json_changes` API, you'd just use ordinary Rails dirty tracking methods instead. (which in most cases would just mean dropping the `. attr_json_changes` from your call).  

I'm not totally sure when I will have time to get to that, but I'd like to prioritize that over fixing existing bugs in `attr_json_changes`, so to be honest I'm unlikely to have time to look into this bug. just being honest about current capacities!

If anyone wanted to try and figure out how to fix this bug in existing implementation, I'd be happy to review a PR.

**Comment by simmerz** [comment]
I've worked around it by comparing the actual changes (not ideal), but if I get to it before you do, I'll put in a PR for sure.

Thanks for the gem in the first place!

**Comment by jrochkind** [comment]
OK, I've had some time to look into this... yeah, this is totally broken. I see why it's broken... the obvious fix makes some other tests fail, so it would require more investment to fix. 

In attr_json 2.0, which I'm hoping to get released in the medium term, I'm hoping to make ordinary rails attribute testing work, so we don't need the custom attr_json dirty tracking. I think I will focus on that instead of trying to fix what's there... but we'll see.
