### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by JensDebergh** [jrochkind/attr_json#152]
Hi!

I'm currently using `attr_json` on a rails project that I would like to upgrade to rails 7. Currently I'm stuck since `attr_json` expects:
`activerecord (>= 5.0.0, < 6.2)`

Do you see any other problems regarding upgrading? I would be happy to whip up a pull request.

Kind regards
Jens

**Comment by jrochkind** [comment]
Hi, thanks for getting in touch!

I could have sworn I had already done that! Although I'm not using Rails 7 myself. Hmm... 

https://github.com/jrochkind/attr_json/commit/c0d66ae6756437ccea53e527255963a6cfdfa864

Looks like I did last December, and it should be released in attr_json 1.4.0?

What version of attr_json are you using?

**Comment by JensDebergh** [comment]
@jrochkind Wow that's fast!

I'm sorry! I made a mistake. I was still using `1.3.0` upgraded to `1.4.0` and it works now!

Cheers!

**Comment by jrochkind** [comment]
Great! Thanks for getting in touch, that was an easy support request to handle! :)
