### ISSUE TITLE
ActiveRecord time_zone_aware_attributes not operative in attr_json date/time types

### ISSUE THREAD

**Issue by jrochkind** [jrochkind/attr_json#16]
ActiveRecord.time_zone_aware_attributes is `true` by default, and what it does is turn all your AR date/time attributes into magical [ActiveSupport::TimeWithZone](http://api.rubyonrails.org/classes/ActiveSupport/TimeWithZone.html) objects that (basically) have the current `Time.zone` zone attached to them. The time might be stored in the db in UTC but it comes back as a TimeWithZone in `Time.zone`.  (you don't even need to save for this to happen, it happens as soon as you set an attribute). 

Our json_attribute `:date` and `:datetime` typed fields do not have this property. They remain plain old ruby stdlib `Time` or `Date` objects, they are not magically turned into `ActiveSupport::TimeWithZone`. 

They are stored in the db always in UTC.  They are _correct_, they don't get the time wrong. If you set a local time, it will be stored in the db in UTC, representing the same moment in time. And it will come back in UTC.  You can convert it to whatever time zone you want for display purposes using ActiveSupport API -- but it won't automatically be that. 

I'm not sure if this matters, it may be okay. On the other hand, it may lead to hard to deal with behavior when letting users edit times in a form (what zone are those times in exactly?). 

We need more info on how important/useful it is before spending time on figuring out how to get our own date/time types to respect `ActiveRecord::Base.time_zone_aware_attributes`.

Feedback welcome. 

There are some tests marked "pending" that would pass if our attr's were properly respecting/implementing `ActiveRecord::Base.time_zone_aware_attributes == true` behavior.

**Comment by DiegoOrejuela** [comment]
@jrochkind I just noticed this when reviewing the information in a registry. It would be very nice to have this feature. Meanwhile, do you think there is any alternative solution?

**Comment by jrochkind** [comment]
I haven't spent time to circle back and look at it.  If anyone else has energy and time, I'd be happy to look at PR's or other suggestions!

**Comment by jrochkind** [comment]
@DiegoOrejuela Actually, something I'm interested in is how [jsonb_accessor](https://github.com/madeintandem/jsonb_accessor) behaves here.  That gem doesn't support nested full models as well, but does let you put a flat list of primitives in a jsonb column. If you do so with a DateTime, does it behave the same as `attr_json`, *or* does it behave the same as ActiveRecord ordinary datetime columns. (Or, I guess, it could do something like neither!). 

If you had time/interest in just trying out jsbon_acessor, and reporting back, especially with some code demonstrating how jsonb_accessor works with regard to this, that would be helpful!

**Comment by jrochkind** [comment]
Looks like jsonb_accessor maybe recently fixed this, we can look to it's code for inspiration. https://github.com/madeintandem/jsonb_accessor/pull/155

Still don't really understand why it's not Just Working via ActiveRecord types!

**Comment by jrochkind** [comment]
On how ActiveRecord does it... a bit devious maybe. Differently than jsonb_accessor I think. 

https://github.com/rails/rails/blob/bb3ab91f4c53c8a45e4a595c1361bde7466c7d97/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb

**Comment by jrochkind** [comment]
This will be in upcoming AttrJson 2.0 release: #164
