### ISSUE TITLE
Test/feedback invited of attr_json 2.0.0.rc1

### ISSUE THREAD

**Issue by jrochkind** [jrochkind/attr_json#182]
A 2.0.0.rc1 release is out. 

This is intended to be a fairly painless upgrade, but it does have some backwards incompatibilities. If it's more painful than I anticipated for anyone, I'd love to know, and see if I can help make it easier. And of course I'd also love to hear about any bugs. 

Is it possible to get any current users other than me to do some real world testing of 2.0.0.rc1? 

The work for 2.0.0 is not currently in `master` branch, it's currently in `dev_v2` branch. You can see release notes here:  https://github.com/jrochkind/attr_json/blob/dev_v2/CHANGELOG.md#200rc1

You should be able to use it in your app just by putting `gem "attr_json", "2.0.0.rc1"` in your Gemfile. 

If I don't hear anything at all from anyone, I may release 2.0.0 final as early as one week from today. But if I hear from anyone, I am happy to delay to give you more time! 

I'm hoping some people watching this repo see this, but I'll take the liberty of tagging some people who have recently interacted with the repo via Issues etc. 

@JensDebergh , @rekapap, @bemueller , @simmerz, @g13ydson, @petergoldstein  -- do any of you still use attr_json, is anyone interested in testing attr_json 2.0.0.rc1, perhaps just by running your CI against it, etc?

### spina

The only major intermediate dependency depending on attr_json I know of is [Spina](https://github.com/SpinaCMS/Spina)

 Y'all appear to include `attr_json` with [no version restrictions in your gemspec](https://github.com/SpinaCMS/Spina/blob/241b13549c5a58a94c20744d41471a2cd9acf396/spina.gemspec#L40).  That means that when I release attr_json 2.0.0 -- with some backwards incompats -- new spina installs will immediately start using it, and existing spina installs will get it next time they `bundle update`. 

You may want to consider changing your gemspec to specify a major version like `"attr_json", "~> 1.0"`, or (once we release it) `"attr_json", "~> 2.0"`. But that's up to you!

In any event, I'd love to work with you to do whatever I can to minimie any trouble the 2.0.0 release causes for you. Does anyone want to test attr_json 2.0.0 with any spina installs? Or make any other suggestions?

I think @Bramjetten is spina maintainers? Taking the liberty of tagging you. 

## kithe

Another intermediate dependency is [kithe](https://github.com/sciencehistory/kithe), which i myself maintain... the only user of kithe I am aware of who is not me is @ewlarson.  Eric, do you still work on/maintain https://github.com/geobtaa/geomg?  Are you interested in testing it out with attr_json 2.0.0.rc1? 

Current kithe _master_ branch works with attr_json 2.0.0.rc1 while still being a kithe 2.x relesae. I am not sure whether to allow kithe to use attr_json 2.0.0 final while stll being a kithe 2.0.x version, or if kithe should bump a major version to allow the new attr_json. Any thoughts?

**Comment by Bramjetten** [comment]
This is nice to see! Thanks for continuing to work on this! I’ll check it out and test Spina with 2.0.0. If nothing comes up I’ll add a version specification :)

**Comment by ewlarson** [comment]
Heya! I do still work with Kithe (still very useful and helpful for us). I can help test things out. Will be in touch.

**Comment by simmerz** [comment]
Use it quite a bit over a number of projects. Will absolutely run it over our ci

**Comment by ewlarson** [comment]
@jrochkind // Okay... I've got a branch of my GEOMG project running Kithe (master) and AttrJson (v2rc1). All of my application tests are passing 🟢. Things look good here for our needs.

The only trouble I ran into was the `AttrJson::Record::Dirty` error, before I noticed your PR in Kithe and pinned my branch to master: https://github.com/sciencehistory/kithe/pull/160

Let me know if you need any further insight here. Sincerely appreciate your work on these tools!

**Comment by Bramjetten** [comment]
SpinaCMS is all green! 🟢

**Comment by jrochkind** [comment]
I'm thinking of dropping ruby 2.7 before the release -- so only supporting ruby 3.0 and up. 

I generally want to support ruby versions as long as I possibly can, and avoid dropping any in a major version if I possibly can. So whatever I launch attr_json 2.0 supporting, I'm going to be stuck with for a while. 

ruby 2.7 is EOL on 31 Mar 2023. 

I'm inclined to drop it for the attr_json 2.0 release, clean break. 

Any feedback or comments welcome.

**Comment by jrochkind** [comment]
Oops, I realize that might mean dropping Rails 6.0 for minimum 6.1 too.... not sure Rails 6.0 supports ruby 3.0.

**Comment by Bramjetten** [comment]
I'd stick to supporting 2.7 as long as it's not actually required to use 3.0 for attr_json.

**Comment by jrochkind** [comment]
Thanks for feedback!  The issue is that I don't really want to drop a ruby version _without_ a major version bump, and I'd like to make major version bumps very rare (2.0 is the first one in 5 years?), so releasing with 2.7 support means that I'm kind of soft-committing to try to keep attr_json working with 2.7 for years, so I can't use useful things like the argument delegator `...`.  But I can potentially support 2.7 for years, it's not necessarily disastrous (glad to have dropped 2.6 though). 

@Bramjetten you might have knowledge of a wider range of installs, using SpinaCMS. Do you have a sense of how common it is, at this moment, for people to be still using Ruby 2.7 and/or Rails 6.0.x?

**Comment by simmerz** [comment]
I'd be inclined to support more or less the same versions of Ruby as the Rails team still have under support. And then reduce that if you *need* features from a higher version to make the library work.

For us, we've got a couple of 2.7 projects that are due to be upgraded soon(ish).

I'd not be averse either to having a major version bump when support ends if you want to ditch it, but even Rails 7.x supports Ruby 2.7 so it's one of those things you probably don't need to think too hard about.

Feel free to ignore the above though - I'm not the one that has to maintain it!

**Comment by jrochkind** [comment]
attr_json 2.0.0 has been released!

It supports ruby 2.7+ and Rails 6.0+
