### ISSUE TITLE
NoMethodError no superclass method on dynamic attr_json declarations with ActiveAdmin

### ISSUE THREAD

**Issue by jrochkind** [jrochkind/attr_json#198]
@garrywilliams reported:

-------------

I add some extra fields, based on a list, to the form. They appear and can be amended, but on update I get the error: `NoMethodError (super: no superclass method `activity=' for #<Thing id: 694281...` (where activity is one of the dynamically added fields).

However, if I then `touch app/admin/things.rb` everything works correctly from then onwards. I suspect this means that I need to add an additional step after I add the fields to make Rails 'aware' of what I've done i.e. I suspect touching the file triggers something that then updates Rails' view of the world.

```
ActiveAdmin.register Thing do
  before_action :add_dynamic_attr_json_fields, only: [:new, :create, :edit, :update]

...

form do |f|
  f.actions
  f.inputs "Thing" do

    ...

    allowed_fields = f.object.get_extra_fields || ""
    allowed_fields = allowed_fields.split(",").map(&:strip)

    allowed_fields.each do |key|
      f.input key, as: :string, input_html: { name: "thing[#{key}]", value: f.object.json_attributes[key] }
    end
    

  controller do

    def add_dynamic_attr_json_fields
      Thing.add_dynamic_attr_json_fields(params[:id])

      thing_id = params[:id]
   
      # Get a comma separated list of field names from the things' thing_groups account
      allowed_fields = thing_groups_things.first.thing_group.account.thing_extra_fields_allowed || ""
      allowed_fields = allowed_fields.split(",").map(&:strip)

      allowed_fields.each do |key|
        unless Thing.attribute_method?(key.to_sym)
          Thing.attr_json key.to_sym, :string, store_key: key
        end
      end

    end

    def update
      add_dynamic_attr_json_fields
      super
    end
```

**Comment by garrywilliams** [comment]
THanks @jrochkind, yes that helps a lot. You're right, I changed my approach to use the json directly and that's working fine. I've learnt a lot from this though, and next time I'll use the attr_json gem as nature intended :) Many thanks!

**Comment by jrochkind** [comment]
@garrywilliams OK, thanks for getting back to me. And thanks for trying it out, and getting in touch! I'm going to close this Issue. 

I personally am also interested in ways to create attributes dynamically at runtime, I understand the motivation. But I haven't really sat down to try to figure out how to dot hat yet that out yet -- it may be that the path of trying to mirror Rails attributes won't work well there, as Rails attributes themselves can't really be created dynamically at runtime.  It's possible it would work best with a pretty different design... but then it might not integrate as well with things that integrate with Rails attributes.  I haven't really figured it out. 

It's also possible that you can dynamically create a _whole subclass at once_ at runtime... but you'd still need to "remember" it somehow so it was still there after a restart... and you still might need to struggle with Rails development mode reloading a bit... and it might just not work. 

These are things I've thought about, I get the use case, I just haven't figured it out myself yet either.
