### ISSUE TITLE
unknown keys for records

### ISSUE THREAD

**Issue by simchikoops** [jrochkind/attr_json#201]
In AttrJson::Model, I can say this:

`attr_json_config(unknown_key: :strip)`

Is there an equivalent for AttrJson::Record? Every time I change the name of an attribute it throws errors, which I'd like to avoid.

**Comment by jrochkind** [comment]
Hi, thanks for getting in touch!

I don't think there is similar configuration for `AttrJson::Record`. I'm not sure if I understand your use case. 

> Every time I change the name of an attribute it throws errors,

I can't get this to happen for me, random unknown keys in the json hash seem to just be ignored by `attr_json`, they don't seem to raise an error for me. 

Can you give me a simple from-scratch code example that shows the problem you are having?

**Comment by simchikoops** [comment]
I had this wrong. As you say, the issue only occurs with models. Thanks for the follow-up.

**Comment by jrochkind** [comment]
Great, thanks for updating us!
