### ISSUE TITLE
weekly CI build failed on May 9: capybara/selenium:  wrong number of arguments (given 2, expected 0..1)

### ISSUE THREAD

**Issue by jrochkind** [jrochkind/attr_json#202]
https://github.com/jrochkind/attr_json/actions/runs/4924461346/jobs/8797516488

I can't figure out what can have possibly changed since last week... it's failing on rails 6.0/ruby 3.0 as well as rails 7.0/ruby 3.2. 

Failure is:

```
     ArgumentError:
       wrong number of arguments (given 2, expected 0..1)
     # ./spec/integration/form_mega_spec.rb:18:in `block (3 levels) in <top (required)>'
     # ./spec/integration/form_mega_spec.rb:11:in `block (2 levels) in <top (required)>'
```

It's not failing on ruby 2.7, so probably keyword arg related... but why would it just have started failing?  Maybe a change in a (non-Rails) dependency. First guess is simple_form , but it's using simple_form 5.2.0, which was released back on Jan 29th, and is same version used in succesful run [last week](https://github.com/jrochkind/attr_json/actions/runs/4859582823/jobs/8662386678)

Need to take some time to investigate;  will maybe start by diff'ing the gem dependencies between succesful run and failed run; as well as just some plain old debugging.

**Comment by jrochkind** [comment]
I did reproduce locally, and it reproduced only after a `bundle update` in my checked out copy, so _some_ change in dependencies is at foot. 

Diffing dependencies between working and broke on ruby 3.2 and rails 7.0...

```
< rspec-rails 6.0.1
< selenium-webdriver 4.9.0
---
> rspec-rails 6.0.2
> selenium-webdriver 4.9.1
```

rspec itself is `3.12.0` in both cases.  i'd guess rspec-rails, but can we confirm? 

Locking rspec-rails to 6.0.1 and running tests again with rails 7.0 and ruby 3.2....   still fails!

Unlocking rspec-rails but locking selenium-webdriver to `4.9.0`...   I'm having weird trouble installing selenium-webdriver 4.9.0 at all, although it doens't look yanked or anything.  VERY WEIRD. 

OK, so def something weird going on with that....

**Comment by jrochkind** [comment]
Already reported to capybara at https://github.com/teamcapybara/capybara/issues/2666

I will try adding `"!= 4.9.1"` to gemfile, and hope they fix it in 4.9.2.

**Comment by kyrofa** [comment]
> Not quite sure what to do.

Update your gemfile to specify `< 4.9.1` on selenium-webdriver:

```ruby
gem 'selenium-webdriver', '< 4.9.1'
```

Then regenerate your appraisal gemfiles. Should be able to remove that once the capybara bug is fixed.

**Comment by kyrofa** [comment]
Yeah that's a legit concern. I was worried your solution might end up in a similar state, but what you ended up doing is obviously a noop, so I'd say you settled on the right path.
