### ISSUE TITLE
PolymorphicModel validations not being run

### ISSUE THREAD

**Issue by LyricL-Gitster** [jrochkind/attr_json#224]
It seems that values with `PolymorphicModel` definitions are not being validated. See examples in this gist:

https://gist.github.com/LyricL-Gitster/cb87fb4cad037068657bd1b4412bb907

In there, you will notice that `good_league` and `bad_league1` seem to behave as expected while `bad_league2` and `bad_league3` - which set the values on the `PolymorphicModel` - do not validate the nested object unless specifically called.

**Comment by jrochkind** [comment]
Hey thanks for filing an Issue, with a good example!

I'll try to find some time to look into this, but I'm honestly not sure when I will find it.  

If anyone else wants to do any debugging to try to get to the bottom of this and/or submit a PR to fix it, I encourage you to!

**Comment by LyricL-Gitster** [comment]
i'll see what i can do 👍
