### ISSUE TITLE
`Can't add, conflict with existing attribute name` on nested collection

### ISSUE THREAD

**Issue by mbajur** [jrochkind/attr_json#230]
Hey! I'm trying to create a nested array for one of my models, here is my code:

```
module Spree
  module ContentBlocks
    class RichText < Spree::ContentBlock
      class Section
        include AttrJson::Model

        attr_json :title, :string
        attr_json :description, :string
      end

      attr_json :sections, Section.to_type, array: true

      attr_json_accepts_nested_attributes_for :sections, reject_if: :all_blank
    end
  end
end
```

Yet, when trying to run the app, i'm getting:

```
Can't add, conflict with existing attribute name `title`: [:title, #<ActiveModel::Type::String:0x00000001160ab600 @true="t", @false="f", @precision=nil, @scale=nil, @limit=nil>, {}]
[attr_json (2.4.0) lib/attr_json/attribute_definition/registry.rb:112:in `add!']
[attr_json (2.4.0) lib/attr_json/attribute_definition/registry.rb:77:in `block (2 levels) in with']
[attr_json (2.4.0) lib/attr_json/attribute_definition/registry.rb:76:in `each']
[attr_json (2.4.0) lib/attr_json/attribute_definition/registry.rb:76:in `block in with']
[<internal:kernel>:90:in `tap']

# On this line from the file above: 
# attr_json :title, :string
```

First of all, my model already has a `title` attribute but this conflict is not about it because when i change `title` in `Section` to, say, `section_title`, the error stays the same but mentioned field is being changed to `section_title` - so it's like attr_json is doing this to itself.

Unusual things that might be related: this is a STI model and it's using Globalize for translations of the core columns/attributes.

I'm on Ruby 3.2.0, Rails 7.1.0 and attr_json 2.4.0

**Comment by mbajur** [comment]
Probably not the best solution but it would quite handy to be able to configure if AttrJson should raise an exception on duplicated attributes or just silently `return` instead. I have a gut feeling the underlying issue is caused by how `Spree` files auto loading works.

**Comment by mbajur** [comment]
It was apparently caused by not including `AttrJson::NestedAttributes` and using `attr_json_accepts_nested_attributes_for` at the same time

**Comment by jrochkind** [comment]
Thanks for the update, I'm glad you figured it out, sorry the error message didn't get you there quicker!

**Comment by mbajur** [comment]
I think making us include that all by ourselves is totally reasonable. I should just read the examples more carefully :)
