### ISSUE TITLE
Update to latest release breaks ActiveModel type registration...

### ISSUE THREAD

**Issue by onomated** [jrochkind/attr_json#30]
I've been using the code @ f221ae050878c6e53039bc7e2006b43ddbadcc7e for over a year now, and decided to give the latest changes a shot.  My custom type registered as:
```
ActiveModel::Type.register(:db_hash, Db::JsonHash)
```
Is no longer resolving due to the change to lookup `ActiveRecord::Type` as opposed to `ActiveModel::Type`.  The comment here looks like the switch was made to support multi-param assignment of date params:
https://github.com/jrochkind/attr_json/blob/master/lib/attr_json/attribute_definition.rb#L43

Can this be changed to look up both?  i.e. Check `ActiveRecord::Type` first then `ActiveModel::Type`?  i.e to something like this:

```ruby
if type.is_a? Symbol
        # ActiveModel::Type.lookup may make more sense, but ActiveModel::Type::Date
        # seems to have a bug with multi-param assignment. Mostly they return
        # the same types, but ActiveRecord::Type::Date works with multi-param assignment.
       begin
              type = ActiveRecord::Type.lookup(type)
       rescue ArgumentError
              type = ActiveModel::Type.lookup(type)
       end
elsif ! type.is_a? ActiveModel::Type::Value
        raise ArgumentError, "Second argument (#{type}) must be a symbol or instance of an ActiveModel::Type::Value subclass"
      end
```

**Comment by onomated** [comment]
I prefer using ActiveModel::Type since its more "generic", and ActiveRecord types are typically bound to data that can natively be assigned to a db column.  I'll look into submitting PRs for both.  Already working on a PR for the ActiveModel fallback.  Trying to get the specs working.

**Comment by jrochkind** [comment]
> I prefer using ActiveModel::Type since its more "generic", and ActiveRecord types are typically bound to data

I thought that was true too, but i'm not sure it really is. And after all a hash kind of _is_ natively assignable to a :json or :jsonb type!   But that's cool. 

I would be happy with just a failing test for the AM::Type issue -- happy to write the func myself! 

I also want to experiment/code read and figure out why AR::Type isn't also finding AM::Type, I really thought it would!

**Comment by onomated** [comment]
https://github.com/jrochkind/attr_json/pull/31

**Comment by jrochkind** [comment]
I'm closing this cause we decided to leave it as is... except there are potentially more slight changes coming here, see #41 and #42 . This stuff interacts with rails in some odd ways. :(
