### ISSUE TITLE
Make the container column to use more explicit

### ISSUE THREAD

**Issue by TylerRick** [jrochkind/attr_json#44]
I'm only just beginning to explore this library—and it looks amazing!—but I wanted to share an initial impression I had while it's still fresh (you only get one chance at first impressions, right?)...

When I first read the examples in the Readme, I was confused because even though I saw you created a jsonb column:
```
t.jsonb :json_attributes
```
, I didn't see that column mentioned in these declarations:
```
attr_json :my_string, :string
...
```

so I was puzzled how it knew which underlying JSONB column to get that data from. I was worried for a second that it might only support getting data from a single JSONB column ... or worse, that the column _had_ to be named `:json_attributes` for thing to work.

Reading on, of course, I found the answer:

> While the default is to assume you want to serialize in a column called json_attributes, no worries, of course you can pick whatever named jsonb column you like, class-wide or per-attribute.

I'm glad there's at least a _way_ to configure which column it uses, esp. on a per-attribute basis, but it bothers me a little that it makes any assumptions about where I want to store that data.

# Arguments for _changing_ API to list container attribute as first arg...

## Verbose if using multiple JSON columns

It definitely makes the API nicer *if* you are only using this with one JSONB column... which I guess is what you're assuming is the _most common scenario_ that you're optimizing for... But it makes it _less nice_ if you're using it with multiple columns. For example,

```ruby
  attr_json :lang,      :string, default: 'fr',              container_attribute: 'locale_preferences'
  attr_json :time_zone, :string, default: 'America/Toronto', container_attribute: 'locale_preferences'
  attr_json :currency,  :string, default: 'CAD',             container_attribute: 'locale_preferences'

  attr_json :send_via_email, :boolean, default: true,  container_attribute: 'notification_preferences'
  attr_json :send_via_sms,   :boolean, default: false, container_attribute: 'notification_preferences'
```

is not as nice or as readable as this would be:

```ruby
  attr_json :locale_preferences, :lang,      :string, default: 'fr'
  attr_json :locale_preferences, :time_zone, :string, default: 'America/Toronto'
  attr_json :locale_preferences, :currency,  :string, default: 'CAD'

  attr_json :notification_preferences, :send_via_email, :boolean, default: true
  attr_json :notification_preferences, :send_via_sms,   :boolean, default: false
```

## Current API more different than necessary from `store_accessor`, etc.

It also makes it different from the `store_accessor` API, which is what folks might have looked into using for their JSONB-backed attributes _prior_ to discovering `attr_json`...

Obviously it can't match the `*keys` API of `store_accessor(store_attribute, *keys)` since it uses argument 2<sub>1</sub> to specify the _type_. But it could at least put the container attribute as the first argument.

These other APIs all list the container/store attribute as the first argument (which doesn't make it better, just makes it more familiar and expected, I suppose)...

https://api.rubyonrails.org/classes/ActiveRecord/Store.html
```ruby
store_accessor :settings, :privileges, :servants
```

https://github.com/joel/json_attributes:
```ruby
json_attributes :office, :address
```

https://github.com/devmynd/jsonb_accessor
```ruby
  jsonb_accessor :data,
    title: :string,
    external_id: :integer,
    reviewed_at: :datetime
```

## Current convention too magical / Explicit would be better

By not even requiring the container/store column name to be specified in the model definition, and just *assuming* it will be named `json_attributes`, it may be a little too magical for some folks, who might prefer to see the relationship with the underlying column name stated explicitly (though I guess those folks can already make it explicit by specifying `container_attribute:` for every attribute) ...

Being explicit about the container/host/store attribute seems like it would be more in line with the philosophy mentioned in [this comment](https://github.com/jrochkind/attr_json/issues/10#issuecomment-375929272):
> ... but the functionality here is only present in a model if you explicitly include `JsonAttribute::Record::QueryScopes`

## Default too presumptuous

Convention over configuration is great and all, but in this case I would worry it could lead people to just automatically assume that only having a single JSON column in their table is _better_, is the _preferred_ way to do it, better supported, etc., without actually considering what column name would make sense for the data they are storing. In other words, people wouldn't want to break from the convention, the "blessed path", so they turn their brains off and just go with the flow?

The current default presumes that most users would/should prefer storing everything in the same column... but is that really the case?

I actually think it would be better in most cases to define as many columns as logically makes sense, in order to better define and organize the data to the extent you know its shape ahead of time, and only use JSONB for the part of the schema that is more variable and would benefit from the flexibility a JSON data type gives you. Like in the example on https://github.com/joel/json_attributes, they name the column `office` because it contains data about its office, such as an address. Or in my example, keeping locale data in a separate column from notification preferences seems preferable to having them all in a single column.

I guess it depends where on the RDBMS-NoSQL spectrum you fall. Taken to the extreme, why don't we just make the default column name be `attributes` and store *all* the model's attributes in that single column? Then you could define your schema entirely with `attr_json`! ;-)

But if you're going to have a default column name, how about something more generic like `data` or something named after what it's for instead of how it's implemented (`json_attributes`)... like:
- `schemaless_attributes`
- `embedded_attributes`
- `miscellaneous_attribute_dumping_ground` ;-)

# Arguments for keeping current `container_attribute:` API

## More declarative / Hides implementation details

I do like how declarative the current API is. It's a little bit like `attr_accessor :attr_name`, which is maybe what you were going for (hoping to evoke).

For the same reason that the main name used is the _attribute_ name and not the `store_name`, having the first "main" argument to `attr_json` be the attribute name keeps the focus on how the end-user of this model will see the attribute.

In other words, it hides the implementation details of where (`container_attribute`, `store_name`) and how (in a JSONB-type column) it will store this attribute in a more out-of-the-way place (at the end of the line)

That seems to be in line with the overall philosophy, as alluded to [in this comment](https://github.com/jrochkind/attr_json/issues/10#issuecomment-375929272):

> I think jsonb_contains is the right name -- and I don't want callers to have to know what host jsonb columns include the json_attribute when making the call ...

# Other option: cleaner DSL for specifying container_attribute

Just thought of another alternative that might be a good compromise between explicit and concise (the main thing having a default column seems to give us)... How about a DSL something like:

```ruby
class OtherModel < ActiveRecord::Base
  include AttrJson::Record

  contained_in_json_attribute :locale_preferences do
    attr_json :lang,      :string, default: 'fr'
    attr_json :time_zone, :string, default: 'America/Toronto'
    attr_json :currency,  :string, default: 'CAD'
  end

  contained_in_json_attribute :notification_preferences do
    attr_json :send_via_email, :boolean, default: true
    attr_json :send_via_sms,   :boolean, default: false
  end
end
```

Downsides:
- either have to use `instance_eval` and mess with `self` or yield something to the block
- what to name it? `contained_in_json_attribute`? `json_attributes_on`?  `json_attributes_in`? `unnest_json_attribute` (like `unnest` from http://trailblazer.to/gems/disposable/api.html)? `container_attribute`?

Upsides:
- groups related things together in the same block and in the same container column, at the same time
- it could be an optional DSL; you wouldn't _have_ to use it

# Conclusion

I hope this was somewhat helpful and I didn't misunderstand something completely. I'm still pretty new to JSONB columns so certainly don't claim to be an expert. I'll try to give the current API a fair chance and see if I still feel the same after I've used it more...

**Comment by jrochkind** [comment]
Thanks for trying it out, and for your extensive notes!  I'm glad you quickly realized you could use with any column name, so maybe the README is good enough already as far as explaining the current func. (It's hard to fit so much in to the README and still be clear). 

For my use cases, I will ordinarily be using it with just one column, so didn't like having to write the column name over and over again. Rather than analogy to `store_accessor`, I thought of analogy to Rails [attribute "macro" method](https://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html#method-i-attribute): `attribute :price_in_cents, :integer`.  Or `attr_accessor` too, sure. 

I think your `contained_in_json_attribute` idea is a pretty good one though. I think I'd call that wrapper method a different name, like `attr_json_container :locale_preferences`.  I like beginning or including in the names of all methods the string `attr_json` to make it clear where the method is coming from. 

the implementation is indeed the trick. I think there _could_ be a little bit of a hacky implementation that doesn't need instance_eval or a different DSL. Something like:

```ruby
def attr_json_container(container_attribute)
   @@current_defualt_container_attribute = container_attribute
ensure
   @@current_defualt_container_attribute = nil
end
```

Then the `attr_json` method could use the class method `@@current_default_container_attribute` as a default, if set. 

This is just an off the cuff idea, not sure if it would work out or not. It is a bit unclean feeling. 

Feel free to send a PR if you'd like though!

**Comment by jrochkind** [comment]
PS: The default column name still seems right to me, but note that you can change it if you like: `  attr_json_config(default_container_attribute: :some_other_column_name)`

**Comment by jrochkind** [comment]
Oh, more justification for the present api, is I wanted `attr_json` to look the same when you are using it for a nested model type, where no container_attribute is applicable. https://github.com/jrochkind/attr_json#nested-models----structuredcompound-data

**Comment by TylerRick** [comment]
Thanks for the reply, and for pointing out the analogy to [`attribute`](https://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html#method-i-attribute)! I guess it's really a hybrid between `attribute` and `store_accessor`.

I guess `attr_json_container` isn't a bad name for a DSL... and good idea for potentially doing it without `instance_eval`.

Thanks for pointing out nested model types justification. Still trying to grok those, but looks super powerful...

**Comment by jrochkind** [comment]
Not going to do this for now, so closing, but thank you for trying out the gem and giving feedback!
