### ISSUE TITLE
should `array:true` values always default to empty array?

### ISSUE THREAD

**Issue by jrochkind** [jrochkind/attr_json#51]
If you define an attribute:

   attr_json :str_array, array: true

And you create a brand new object `SomeModel.create!`. 

* It has no key stored in the json hash for `str_array` at all
* if you look at it (now or after later fetch), `model_intance.str_array` is `nil`, not `[]`. 

This adds some annoyance when writing view or other code that wants to iterate over it. `model_instance.str_array.each` will of course be a `undefined method `each' for nil:NilClass`.

You could define it to have a default of the empty array yourself:

    attr_json :str_array, array: true, default: -> { [] }

It's a bit annoying to do that for every `attr_json` you define. 

This also means that `SomeModel.create!` will, all by itself, store a key in the serialized json hash for `str_array` with the empty (json) array as a value. 

What do we want attr_json to do by default? Or as an option?

If any other users of attr_json are reading, feedback welcome!

**Comment by onomated** [comment]
I think this should be opt in, as I do like that non-specified fields don't litter my json data.  In some domains, null may have a meaning different from empty array.
My two cents.

Thanks!

**Comment by jrochkind** [comment]
It's _possible_ I can make the typecasting so nil always _reads_ as an empty array, even though it's not serialized in the same db. 

But I guess that would have the same concern. And I'm not totally sure I can do that anyway haha.

**Comment by jrochkind** [comment]
OK, based on @onomated's feedback, we'll leave this as-is for now! Thanks!

**Comment by Gambitboy** [comment]
Nvm, as I opened the code to look at the array, I ran into `default: AttrJson::AttributeDefinition::NO_DEFAULT_PROVIDED ` 😆
