### ISSUE TITLE
Allowing arbitrary hash types

### ISSUE THREAD

**Issue by nhemsley** [jrochkind/attr_json#52]
Hello,

I would like to be able to store arbitrary-depth model information, but it is not clear if attr_json handles this gracefully (if at all??)

say:

class User
  include AttrJson::Record

  attr_json :full_name, :string
  attr_json :data_dump, :????
end

I want instantiated_user.data_dump to accept an arbitrary hash.

Is this at all possible? or should I just use a separate json field (I just realized this as I was posting).

Thanks for the nice gem, and in advance,

Nick

**Comment by jrochkind** [comment]
if I understand what you mean, It should be possible, but we need to try it out, make sure it works well, document, and test it better. 

You can help by trying it out and reporting back. Try this and let us know?

```ruby
class User
include AttrJson::Record

attr_json :full_name, :string
attr_json :data_dump, :json
end
```

This is actually using ActiveRecord's already existing `:json` type registration. I haven't tried it yet, had time to think of it, but not to try it. It might not work quite right. (Now I'm realizing you might end up with your `data_dump` serialized as a _string_ inside a json hash, which is not really what you want, hmm). 

If it doesn't work quite right, we can add just a bit of code to provide for this feature. If I understand what you're asking for. A couple other people have asked for it (#32), so I should try to find time to make it so. 

Thanks for checking out this gem and giving feedback!

**Comment by nhemsley** [comment]
Hey,

Thanks for the propmt reply & ideas. I will look at trying this in my models, or (probably) add some test code to att_json to ascertain the behaviour, later on this day hopefully.

adding a json field  directly works for now.

**Comment by nhemsley** [comment]
Turns out something like the following works:

```
#subclassing Value works as the serialize/deserialize is a no-op
class JsonHash < ActiveModel::Type::Value
end

#in a rails initializer
ActiveRecord::Type.register(:json_hash, JsonHash)

models/my_model.rb
class MyModel < ActiveRecord::Base
  include AttrJson::Record

  attr_json :data_dump, :json_hash
end

```
or 

```
class MyModel < ActiveRecord::Base
  include AttrJson::Record

  attr_json :data_dump, ActiveModel::Type::Value.new
end

```

**Comment by jrochkind** [comment]
Dup of #32, and as you verified in #61 and doc'd in #56, already possible with, as you point out, `attr_json :data_dump, ActiveModel::Type::Value.new`. 

Will merge the tests and docs shortly, but for now closing this, as it's already possible without attr_json code changes.
