### ISSUE TITLE
Creating a CollectionProxy using `.to_list_type`

### ISSUE THREAD

**Issue by volkanunsal** [jrochkind/attr_json#70]
Hey @jrochkind,

I have this usecase that I wanted to run by you. I often use array attributes to store a collection of lightweight AttrJson models with an id field. This is much more ergonomic than creating a new table, especially if the collection will always be queries through the parent record. But querying over these arrays is pretty tedious, as it involves typical find/select workflow, and I have to write the finders on the parent. Creating new instances of these models is even more tedius. I end up building a lot of repetitious CRUD methods on the parent class. 

A simpler alternative I've come up with is to create a Collection type for the model, and write custom  serialize/deserialize methods to handle the conversion. This allows me to write custom finder methods like this:

```ruby
module Product
  class Collection
    include Enumerable

    def find_by(**kwargs)
      # ...
    end

    def where(**kwargs)
      # ...
    end
  end

  class Type < ActiveRecord::Type::Value
    def type
      :jsonb
    end

    def cast(value)
      Collection.new(value)
    end

    def deserialize(value)
      return Collection.new(value) if value.kind_of?(Array)
      decoded = ::ActiveSupport::JSON.decode(value) rescue []
      Collection.new(decoded)
    end

    def serialize(value)
      case value
      when Array, Collection
        ::ActiveSupport::JSON.encode(value)
      when Hash
        ::ActiveSupport::JSON.encode(value.values)
      else
        super
      end
    end
  end
end
```

This is pretty much what Rails' `CollectionProxy` module does. But creating a Collection type for every model is pretty tedious, too! So that got me thinking what if there was a feature that rolled out a Collection type for an AttrJson model? The interface would be something like this:

```ruby
attr_json :products, Product.to_list_type, default: Product.collection.new
```

Thus, anyone would be able to query over array attributes as seamlessly as they can query over Hash attributes. 

What are your thoughts?

**Comment by jrochkind** [comment]
I am having trouble understanding what this is for. 

What is the "typical find/select workflow" you find tedious?  Just `some_model.some_attribute.find { |obj| obj["id"] }`, is that what we're talking about?

That doesn't seem that tedious to me,but if I'm the right track, what is the less tedious code your implementation makes possible? Just `some_model.some_attribute.find(id: "foo")`, is that right?

That improvement to me does not seem worth any additional code to maintain, in attr_json, and add to the documentation overload for. 

I'm interested in understanding more, but honestly, I'm pretty sure no matter what you tell me I'm going to think it's not something suitable for attr_json.  I am reluctant to add special purpose code to save you a few characters of typing at the cost of more code that can have bugs to maintain, and more complexity in attr_json.

**Comment by volkanunsal** [comment]
Fair point. Increased complexity is a big drawback. It seemed like a natural fit, since there is already a `to_type` method added by `AttrJson::Model`. All this would do is to add some of the interface on an `ActiveRecord::Relation` to make it easier to interface with an array of model instances. 

It's not just matching against an id, but matching against any property. Just to give you an example, I have this type called `MarkerColor::Collection` where I have to match an object against 4 attributes. That's really tedious. It's the kind of thing that would be easy with SQL, but I can't use a different table because it would cause an N+1 bug. So the code gets really hairy. 

Another good use case is the CRUD operations. Take a look at this code I wrote today to manage a new class:

```ruby
def new_google_form_button(o = {})
  GoogleFormButton.new(o)
end

def create_google_form_button!(o = {})
  record = GoogleFormButton.new(o)
  self.google_form_buttons << record
  save!
  record
end

def destroy_google_form_button!(record_id)
  btn = google_form_buttons.select { |v| v.id == record_id }
  self.google_form_buttons = google_form_buttons.reject { |v| v.id == record_id }
  save!
  btn
end

def update_google_form_button!(record_id, o)
  btn = google_form_buttons.find { |v| v.id == record_id }
  return if btn.blank?
  o.each do |key, value|
    btn.send("#{key}=", value) if btn.respond_to?(key)
  end
  updated_btns = google_form_buttons.reject { |v| v.id == record_id }.concat([btn])
  self.google_form_buttons = updated_btns
  save!
  btn
end
```

I'm thinking there could be a common abstraction layer over all these collection types...

**Comment by jrochkind** [comment]
I see your point, but I don't think I'm interested in building this into attr_json at this time. It's already a lot of code to maintain (and features to document and for someone to learn). 

I *am* interested in making sure attr_json supports you doing this yourself though. 

Your example supports this with a custom ActiveModel::Type on the container. To support that, attr_json might need to allow the user to specify a custom container type, which it doesn't really now. That might be useful for supporting the jsonb-merge stuff too, depending on how that ends up being implemented. That might be a useful general feature. 

**However** I wonder if there's an easier way for you to add this to your record, without needing a custom ActiveModel::Type on the container. What if you just override the method that you want the finders (via a "CollectionProxy") on? Just in your model?

```ruby
def json_attributes
   MyWeirdCollectionProxy.new(super)
end
```

Could you get the func you want locally like this, in existing attr_json?

In general, my top priority for attr_json at the moment is giving some attention to your jsonb+merge stuff. I'm sorry I haven't had time to do that yet, trying to find the time with my day job etc! But I think that is an important and useful feature, whether it ends up in attr_json or a separate gem, I want to find time to try to make it as solid and maintainable and few-lines-of-code as possible (according to my perspective anyway); thanks for doing the work to get that started, I hope to find time to take it further.

**Comment by jrochkind** [comment]
Closing this for now, not currently interested in implementing, but feel free to re-open and/or file another issue or PR if you still have concerns or questions or arguments!
