### ISSUE TITLE
Have a changelog

### ISSUE THREAD

**Issue by FunkyloverOne** [jrochkind/attr_json#72]
Hey there! Looks like an awesome gem!

But I didn't see any kind of changelog file here. And it already has 7 releases. I believe it would be nice to start logging what's new in new releases. If you need some template, here's one:
https://keepachangelog.com/en/1.0.0/

**Comment by jrochkind** [comment]
Thanks for the suggestion!

I had planned to not maintain a changelog until 1.0, it's extra work to maintain the log. But it may be time for both of those things, or a changelog even if not 1.0. 

I'll consider it, not sure!

@FunkyloverOne can you share info with me your interactions with attr_json? Are you currently using it? Considering using it? And for what sort of use case?  If you've written code with it at all yet, how have you found it? I don't have a lot of info in what people are using or wanting to use attr_json for, it's helpful for me to know what people are doing!

**Comment by FunkyloverOne** [comment]
@jrochkind I personally do not use this gem yet, but my colleague is currently playing with it around. The use case is avoiding unnecessarily complicated normalized RDBMS schema.
You know, having some Mongoid-style embedded models in RDBMS.

So far my colleague have noticed strange behavior, here:
```ruby
active_record_model.update(embedded_model: { field1: '1', field2: '2' })
active_record_model.embedded_model
# => #<EmbeddedModel @attributes={"field1"=>"1", "field2"=>"2"}>

active_record_model.update(embedded_model: { field1: '222222'})
active_record_model.embedded_model
# => #<EmbeddedModel @attributes={"field1"=>"222222"}>
```
You see? It did not preserve `field2`. We expected it be untouched, yet it's now gone.
Is it supposed to behave this way?

**Comment by jrochkind** [comment]
@FunkyloverOne 

Hmm, I think that is expected, for better or worse. If you set the whole hash (including with `update`) -- that's the whole hash!  AR `update` under the hood will just do `active_record_model.embedded_model = { field1: '222222'}` (this is not attr_json-specific code, just what AR does for `update`), so you are setting `embedded` model to that hash. 

It's possible we could fix it, or provide alternate API, I'm not sure. 

Alternately you can do either of these:

    active_record_model.embedded_model.field1 = '222222'
    active_record_model.update(embedded_model: active_record_model.embedded_model.to_json.merge( field1: '222222')))

Or MAYBE this will work (or if not we can probably make it work):

    active_record_model.embedded_model.update(field1: '222222')

Feel free to open up a separate GH issue for this or anything else you come accross. 

Thanks for checking out attr_json!

**Comment by jrochkind** [comment]
I am about to release this as 1.0.0, and will try to use a CHANGELOG subsequently. There will be no CHANGELOG for pre-1.0 releases though, so we'll start out with a blank one.
