### ISSUE TITLE
Getting error when setting a default value to a nested object

### ISSUE THREAD

**Issue by caiofilipemr** [jrochkind/attr_json#84]
### Problem

I am getting an error when I set a default value to a nested object (e.g. `attr_json :nested_type, NestedType.to_type, default: NestedType.new`).

The error:

```
NoMethodError: undefined method `attributes' for #<Object:0x00005652820c1810>
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/attr_json-1.0.0/lib/attr_json/model.rb:248:in `=='
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/attr_json-1.0.0/lib/attr_json/attribute_definition.rb:78:in `!='
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/attr_json-1.0.0/lib/attr_json/attribute_definition.rb:78:in `has_default?'
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/attr_json-1.0.0/lib/attr_json/type/container_attribute.rb:52:in `block in deserialize'
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/attr_json-1.0.0/lib/attr_json/type/container_attribute.rb:47:in `each'
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/attr_json-1.0.0/lib/attr_json/type/container_attribute.rb:47:in `deserialize'
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/activemodel-6.0.2.2/lib/active_model/type/helpers/mutable.rb:8:in `cast'
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/attr_json-1.0.0/lib/attr_json/type/container_attribute.rb:19:in `cast'
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/activemodel-6.0.2.2/lib/active_model/attribute.rb:174:in `type_cast'
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/activemodel-6.0.2.2/lib/active_model/attribute.rb:42:in `value'
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/activemodel-6.0.2.2/lib/active_model/attribute_set.rb:41:in `fetch_value'
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.2/lib/active_record/attribute_methods/read.rb:40:in `_read_attribute'
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.2/lib/active_record/attribute_methods/read.rb:18:in `json_attributes'
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/attr_json-1.0.0/lib/attr_json/record.rb:182:in `public_send'
    /home/caiofilipemr/.rvm/gems/ruby-2.6.3/gems/attr_json-1.0.0/lib/attr_json/record.rb:182:in `block (2 levels) in attr_json'
```

Following the stack, the exception is thrown in [`other_object.attributes == self.attributes`](https://github.com/jrochkind/attr_json/blob/9577153ae37faeeb4dbca1ba36bb89a4418121ed/lib/attr_json/model.rb#L246-L249), which is called by [`AttributeDefinition#has_default?`](https://github.com/jrochkind/attr_json/blob/9577153ae37faeeb4dbca1ba36bb89a4418121ed/lib/attr_json/attribute_definition.rb#L77-L79) passing `@default` and  `NO_DEFAULT_PROVIDED`. This is weird, because, if I understood correctly, `NO_DEFAULT_PROVIDED` will always [be an empty `Object`](https://github.com/jrochkind/attr_json/blob/9577153ae37faeeb4dbca1ba36bb89a4418121ed/lib/attr_json/attribute_definition.rb#L9) and, therefore will never have an `#attributes` method.

### Script to reproduce

Here is a script to reproduce the error. Just save into `.rb` file and execute `ruby filename.rb`:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", '6.0.2.2'
  gem 'sqlite3'
  gem 'attr_json'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :examples, force: true do |t|
    t.json :json
  end
end

class DateSpan
  include AttrJson::Model

  attr_json :years,  :integer
  attr_json :months, :integer
  attr_json :days,   :integer
end

class Example < ActiveRecord::Base
  include AttrJson::Record

  attr_json :date_span, DateSpan.to_type, default: DateSpan.new
end

class BugTest < Minitest::Test
  def test_default_value_on_a_new_example
    Example.new.date_span
  end

  def test_default_value_on_a_existing_example
    Example.create!.date_span
  end
end
```

PS: we are using `postgresql` in our code, the `sqlite3` here is just for the sake of simplicity.

**Comment by jrochkind** [comment]
Interesting, that's too bad.  Thanks for the good report. 

I haven't had a chance to look at this yet, but for more info and as a potential workaround, can you try: `default: NestedType.new.as_json`?

**Comment by caiofilipemr** [comment]
> I haven't had a chance to look at this yet, but for more info and as a potential workaround, can you try: `default: NestedType.new.as_json`?

It worked! Thank you :)

**Comment by jrochkind** [comment]
Aweosme, I would still consider this a bug, and would like to fix this bug, and will leave the issue open. But with a workaround, it might take me a bit of time to get to this. 

Thanks for trying out attr_json and letting me know about problems!

**Comment by Bramjetten** [comment]
Not entirely sure if related, but I can't seem to save nested objects at all when using `array: true` and `default: []`.

**Comment by jrochkind** [comment]
@Bramjetten I think you want, `default: -> { [] }` (a proc object that returns an empty array), for the same reason you need to do something similar when setting a standard Array's default. 

I definitely do that in my own project without trouble. If you're still having trouble with it, please file a separate issue, ideally with an isolated reproduction (say, a failing test case). 

Thanks!

**Comment by jrochkind** [comment]
Hey, I found some time to look at this, and I think actually, it's not a bug, but a common error. Similar to conversion with @Bramjetten above, what you *actually* want is:

    attr_json :date_span, DateSpan.to_type, default: -> { DateSpan.new }

Note we're passing a proc instead of just `DateSpan.new`. 

This proc version is actually [tested in existing specs](https://github.com/jrochkind/attr_json/blob/dcfbb97b1875eb73a1cd84b099f6d77dbca5ab18/spec/record_with_model_spec.rb#L315-L333)

The problem with your version is that it will be executed at class load time, and instantiate one single instance of `DateSpan`, and then try to re-use that *same* instance over and over again as the default value for every single record.  

I'm not sure why it resulted in the particular error you got, but it's not a good idea. This is very similar to a [very common gotcha with stdlib ruby Hash](https://michaeljherold.com/2018/08/20/hash-default-value/). 

However, it's also true that even I didn't notice this at first -- it could probably use some better documentation, but we already have SO MUCH documentation that I"m not sure where I can add it that will actually get noticed -- but I'll look around!

The `.as_json` is still a good workaround, becuase while it will use the same Hash as a default -- the Hash immediately gets cast into an object, a unique new object for every instance, so it works.

**Comment by jrochkind** [comment]
There's ALSO a bug you found here, the particular "undefined method `attributes'" is some kind of bug I'd like to fix -- but it still wouldn't do what you want, and would end up causing confusing problems!

**Comment by caiofilipemr** [comment]
Thank you for the excellent answer!

Using a `proc` looks great and makes sense. 

The documentation you are adding is getting great!

And thank you for making the effort to create and maintain this wonderful _gem_.

**Comment by jrochkind** [comment]
See also #90, fixing the bug that you actually ran into here (thanks for reporting!).

**Comment by jrochkind** [comment]
Hmm, why can't I figure out where 5b89874 went, my commit to improve docs... somehow seems to have gotten lost and not be on master? I seem to have confused myself with branches or something.
