### ISSUE TITLE
Unable to use uniqueness validation from AR

### ISSUE THREAD

**Issue by simmerz** [jrochkind/attr_json#88]
AR's default uniqueness validation queries the database and expects the column to be there. Of course, because it's a jsonb attribute, it isn't there.

**Comment by jrochkind** [comment]
Good point!  I don't think there's probably anything super feasible for us to do about that. Do you have thoughts?  

I think this may just be the way it is. It's not feasible to make an attr_json attribute absolutely universally just as if it were a real column. 

One of my goalposts has been the existing ActiveRecord [serialization](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html) feature. Using that feature, you wouldn't be able to use uniqueness validations on individual attributes of the object either.

**Comment by jrochkind** [comment]
I could imagine a custom uniqueness validation that would work, but you'd want to make sure to have the right postgres indexes created to keep it efficient with a lot of data (if you might have a lot of data). Exactly what the right indexes are might depend on your other usage patterns. There's still some stuff you have to figure out with postgres jsonb features. 

I think it might be out of scope for attr_json right now, but if you are able to figure out a good way to do it, I'd love to have it documented in wiki or source docs?

**Comment by simmerz** [comment]
Yeah, like you say, I think the only way is a custom validator, say `jsonb_uniqueness: true` for pg. YMMV with other RDBMSs.

**Comment by jrochkind** [comment]
Cool. I'm going to close this ticket for now, but if you work on doing that (I don't think it needs any support from attr_json, I think it can be done separately just as well as part of attr_json), please feel free to share it somewhere here. this ticket, wiki, PR for docs with it as a suggestion, whatever. 

I would recommend paying attention to postgres jsonb indexing if you want it to be a generalizable solution for larger tables.

**Comment by jrochkind** [comment]
Thanks for getting in touch!
