### ISSUE TITLE
Feature request: add option to skip default value storage for sparse data types

### ISSUE THREAD

**Issue by giovannibonetti** [jrochkind/attr_json#97]
Hi! Thanks again for the awesome gem! It is very useful, specially combined with STI - since each subclass has different attributes.

Anyway, in the project I'm working on I have the following use case:
```ruby
class MyModel < ApplicationRecord
  include AttrJson::Record

  attr_json :my_nested_object, MyNestedObject, array: true, default: ->{ [] }
end

class MyNestedObject
  include AttrJson::Model

  attr_json :a, :integer, default: 0
  attr_json :b, :integer, default: 0
  attr_json :c, :integer, default: 0

  attr_json :d, :integer, default: 0
  attr_json :e, :integer, default: 0
  attr_json :f, :integer, default: 0

  validates :a, :b, :c, presence: true
  validates :a, :b, :c, :d, :e, :f, numericality: { greater_than_or_equal_to: 0 }
end
```

In this example we have 2 x 3 = 6 fields. And of these, only `a`, `b` and `c` are usually filled out. On the other hand, fields `d`, `e` and `f` are present only in some rare circunstances.

I was wondering if it would be possible to instruct `attr_json` to skip the fields `d`, `e` and `f` from storage when they were not given and have the default value (in this case, zero). It could be specified like this:

```ruby
class MyNestedObject
  include AttrJson::Model

  attr_json :a, :integer, default: 0
  attr_json :b, :integer, default: 0
  attr_json :c, :integer, default: 0

  attr_json :d, :integer, default: 0, store_default: false
  attr_json :e, :integer, default: 0, store_default: false
  attr_json :f, :integer, default: 0, store_default: false

  validates :a, :b, :c, presence: true
  validates :a, :b, :c, :d, :e, :f, numericality: { greater_than_or_equal_to: 0 }
end
```

That way, if a user saved a record with value `{"a": 1, "b": 2, "c": 3}`, only these fields would be present in the database.

The motivation for that is that I'm working with a sparse data set, where each object has about 25 fields, of which only 13 will be filled in over 90% of the cases. Do you think it is worth it to avoid storing them? If so, do you have a suggestion on how that could be implemented? I can try making a PR for that if you point me the right direction

**Comment by jrochkind** [comment]
Hi, thanks for trying out attr_json and getting in touch!

My initial reaction is that is a bit too special-purpose a feature to add; the attr_json is already kind of complicated. There are a lot of conditional logic branches like this people could or have asked for, if we add them all in the code gets even more complicated. 

Ideally there would be a way for you to handle it with custom code somehow though. I'm not sure. 

Another issue is that I'm leaning toward trying to, in a future release, get rid of `AttrJson::Model` entirely in favor of using `ActiveModel::Model` and `ActiveModel::Attributes`. The latter is unfortunately under-documented, but built into Rails -- but wasn't yet when attr_json was first released. I'd like to remove some code from AttrJson in the future, in favor of using code already built into Rails. Which wouldn't be compatible with exactly this approach. 

But what I'm wondering is if there's a way to do it with a custom _type_ decleration instead. When you declare:

    attr_json :my_nested_object, MyNestedObject.to_type, array: true, default: ->{ [] }

(note you had left out the `to_type` in your sample).  You are using the ActiveModel::Type built into attr_json that lets an AttrJson::Model be serialized/deserialized.  Hypothetically, you could instead write your own type, perhaps a a sub-class of the one built into AttrJson, calling it might look something like:

    attr_json :my_nested_object, SparseStoringModelType.new(MyNestedObject), array: true, default: ->{ [] }

Or

    attr_json :my_nested_object, SparseStoringModelType.new(MyNestedObject, sparse: [:d, :e, :f]), array: true, default: ->{ [] }

You'd have to implement that `SparseStoringModelType` yourself, to do what you want. Then I guess if AttrJson later switches to using `ActiveModel::Attributes` instead, you might need to refactor your code a bit. 

Is it worth it to do this?  I guess that's up to you; personally I am not feeling great about the trade-off of more complicated code to maintain in return for... somewhat less bytes in the db?  

I am also curious if you actually have a data where you have noticed a bottleneck with these bytes, where you actually have too many bytes on desk or in network traffic or something, and actually have a need to avoid storing them, or if this is just theoretical/hypothetical?

Another approach that might work is just overriding the methods in your model class. 

```
class MyNestedObject
  include AttrJson::Model

  attr_json :d, :integer

  def d
    super || 0
  end
end
```

That might work; although it might not, I haven't tried it. I wouldn't be totally shocked if ActiveRecord ends up treating that the same as the default and writing the `0` to the db too, I'd have to try it. 

This is my initial reaction! Thanks for getting in touch!

**Comment by giovannibonetti** [comment]
Thanks for the response!

I understand your point, it is not worth it to make the code more complicated. I'll see if it really makes a huge difference in my case, and try out the ideas you pointed out.

In case I end up implementing `SparseStoringModelType` I'll report it here for reference.

Have a nice day! 😀

**Comment by jrochkind** [comment]
By the way, attr_json 2.0 now skips serialization when values are _nil_ and _have no default_. 

I just ran across this old issue searching for something else, and realize I have gotten _closer_ to it. 

Right now it won't skip values that have defaults, even if the current value matches default... but I realize I got a lot closer to it, in pursuit of making serialized hashes sparser, indeed -- and potentially could consider it again now.  One possible complication could be that attr_json supports defaults as _procs_ that are executed; that might make it harder to reliably and performantly determine when the current value 'is' the default.. it might actually make it infeasible. I don't think we want to be executing a default proc on every save for performance (and other!) reasons?

But @giovannibonetti I'm curious if you are still around and still interested in this -- how important it ended up being -- we could potentially re-open it and re-consider.

**Comment by giovannibonetti** [comment]
Hi @jrochkind!

Those seem like good points. If I were to implement it, I think I would try to keep it simple and only handle the case where the default is a fixed value like a number or a string.

Anyway, I'm not working on that project anymore. I'm one of those people that try to optimize database storage as much as possible, but in that case JSON is not the ideal choice anyway. I think I read somewhere that null values in regular Postgres columns are almost "free", taking up a single bit in a mask that tells the database which fields are non-null. In retrospect, I should have probably gone with a standard relational table to optimize storage in that case.

Wish you good luck with whatever direction you choose to move the project forward!
