### ISSUE TITLE
Custom types inside Model types don't deserialize correctly

### ISSUE THREAD

**Issue by bradleesand** [jrochkind/attr_json#99]
I have an `ActiveRecord::Type` that encrypts the value in the database. It works correctly when I use it on an ActiveRecord with `attribute :password, :encrypted` and even with `attr_json :password, :encrypted` but it doesn't work when the `attr_json` is inside an `AttrJson::Model`. I think the issue is because `AttrJson::Type::Model` just calls `cast` from `deserialize` [here](https://github.com/jrochkind/attr_json/blob/e95504ea824eb60a30eb6a5b2af2a93995cac418/lib/attr_json/type/model.rb#L61). The way I see it, `cast` is supposed to take in a user value while `deserialize` is supposed to take in a value from the database, so it doesn't make sense to me to call `case` from `deserialize`.

```ruby
class EncryptedType < ActiveRecord::Type::Value
  def deserialize(value)
    decrypt(value)
  end

  def serialize(value)
    encrypt(value)
  end

  def cast(value)
    value
  end
end

ActiveRecord::Type.register(:encrypted, EncryptedType)

def UserType
  include AttrJson::Model
  attr_json :password, :encrypted
end

def Account < ActiveRecord::Base
  include AttrJson::Record
  attr_json :user, UserType.to_type
end
```

**Comment by jrochkind** [comment]
Hi, thanks for giving the gem a try and giving feedback!

Having `deserialize` just call `cast` was actually taken from the ActiveModel::Value base implementation: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/type/value.rb#L31-L33

In many general cases, deserialize and cast are the same thing, and the default implementation as you can see above has them as the same implementation.  As far as I could tell they were the same implementation/thing for the `AttrJson::Type::Model` too -- I didn't see any reason for them to be different. 

You may have found a reason but I'm not totally following what the fix would be. Do you have a sense of what the fix would be, how `deserialize` should be implemented differently?  I'd be interested to see a PR. And for immediate use, you could always make your own sub-class of `AttrJson::Type::Model` where you override `deserialize` to do something different, and use it immediately.... but the hard part is figuring out what the "something different" is that will still work right, but also fix things for your use case. Do you have a sense of what that implementation is?
